### ISSUE TITLE
fix: 🤔 accessible color combinations

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#1130]
## Current behavior
Background colors disappeared [on this board](https://www.figma.com/design/VTztxQ5pWG7ARg8hCX6PfR/Solid-DS-–-Component-Library?node-id=10157-8019&t=B2ToSzJRg3oega3y-11)

## To do
Pls dig why this error occurs and fix it. 

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
@yoezlem since Van has time ... could we execute this in the current sprint? Should be only 1 SP

**Comment by yoezlem** [comment]
👍🏻

**Comment by van-nguyen-ht** [comment]
@coraliefeil 
Hi Coralie, I have fixed/filled the colors. The reasons I deduce could be: 
-old color tokens i.e.: background.warning -> I relinked all
-the color was applied directly on top of the group instead of the square shape layer "ui-color" which doesn't always work with color tokens -> I got rid of all colors applied to the group and reapplied tokens to the layer instead.
