### ISSUE TITLE
fix: 🤔 sd-brandshape variants not working

### ISSUE THREAD

**Issue by niksan9** [solid-design-system/solid#1216]
## Current behavior
The variants "border-primary" and "border-white" do not work on the ui sites and lead to unwanted styling (see screenshot attached)
![image](https://github.com/user-attachments/assets/679e8a21-d201-4f4d-b10b-abe0dc945914)

## Expected behavior
The variants should add the respective border like in the sd storybook

## Steps to reproduce
Either a) go to [the ui sparen site](https://www.union-investment.de/sparen) and change the variant of the brandshape to either "border-primary" or "border-white"
or b) checkout feat/PB2B-10796-migration-cms-container in the ui repo and start the storybook to see the problem on [this story](http://localhost:6006/?path=/story/cms-components-cms-container--container-with-border) (you may have to change the url port based on your config)

## Technical Information
The problem was found both with an older version (3.6) as well as with the newest 3.8.1 version

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by karlbaumhauer** [comment]
@niksan9 I unfortunately can only have a look into the HTML (currently no dev is available to go deeper) and what I found is a missing `class="fill-transparent"` on the div inside the sd-brandshape on your page:
![image](https://github.com/user-attachments/assets/301ffd57-31a3-4c1b-9324-2ec3f265189e)
compared to our storybook sample:
![image](https://github.com/user-attachments/assets/8afea83b-aca6-4669-a9f9-c23a8677655a)

I cannot say right now where the issue is located but maybe it helps you as a quick fix.

**Comment by yoezlem** [comment]
We found the error. The wrong version was used; the brandshape outline variants have been accessible since version 3.9.0, but version 3.8.x was used instead. The ticket will be closed.
