### ISSUE TITLE
feat[dev]: ✨ implement A11y improvements for Mark Template

### ISSUE THREAD

**Issue by yoezlem** [solid-design-system/solid#1532]
## Description
This task describes the Storybook implementation for the Mark template as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for the Mark template can be found here: [Mark Notes](https://www.notion.so/matuzo/Mark-112f3f6e1bc08002baa2f403b9dab4bc).

-----------------

## Comment
See [@sd-mark](https://www.notion.so/sd-mark-111f3f6e1bc0802f83c8eef988efb114?pvs=24)

## Additional Information
- Before working on this template ticket, please finish the main component ticket first. This template ticket is linked to the component and will be resolved once the component's A11y improvements are completed:
#1613

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [x] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [x] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by coraliefeil** [comment]
Pls remove template "Leadtext with Mark" completely.

https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/templates-mark--docs#leadtext%20with%20mark

Due to fluid typography the regular text is getting too small on mobile and therefore does not comply anymore with WCAG 2.2. Level AA18.

The other templates are fine.
