### ISSUE TITLE
feat: ✨ add sd-table

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#18]
## Description
We provide an `sd-table-cell` CSS component that allows developers to quickly build tables with a defined style. (For Design it's a component, as this allows quick prototyping, for Development it makes sense to provide a CSS style instead) The element doesn't handle semantics like `td`, `th`, `tr` etc. which is completely handled by the LightDOM instead. This serves a11y and a much easier implementation.

## API
[Figma branch](https://www.figma.com/file/fjET4Lt7qESao1bnop9jtX/sd-table-V.0.0.3?type=design&node-id=3738-22115&mode=design)

```
sd-table-cell--divider (always on the right hand side)
sd-table-cell--transparent (color variant)
sd-table-cell--white (color variant)
sd-table-cell--primary-100 (color variant)
sd-table-cell--neutral-100 (color variant)
sd-table (remove built-in html styles)
```

Currently in Figma two components are build, which only difference is `bold` or `not-bold` for header vs. `not-header`. We decided to merge this in a single `sd-table-cell` component and let the users mark headers with bold theirself.

On top we need to provide a `sd-table` class, which just removes all default styling in a table, so that paddings and borders etc. are cleared before using our component.

## Note: 
Align with @solid-design-system/design before merging to be final at the same time.

### Samples:
- [x] Sortable Table (always using a button to wrap the icon => a11y will break)
- [x] Simple Table With Vertical Lines
- [x] Simple Table, First Column Fixed => just add a comment (coming as soon as we have the sd-scrollable)
- [x] Multi Select Table => just add a comment (coming as soon as we have the sd-scrollable)

update Jira Ticket https://jira.apps.union-investment.de/browse/UMAGDXC-466 when component concept is ready.

[Figma Component, Documentation, Hand-off](https://www.figma.com/file/fjET4Lt7qESao1bnop9jtX/sd-table-V.0.0.3?type=design&node-id=3738-22115&mode=design)

TODO:
- [x] create follow-up ticket for fixed-column sample
#376
- [x] create follow-up ticket for multi-select sample
#376

**Comment by coraliefeil** [comment]
We could talk about the sd-table in the next refinement and see if it is ready for implementation.

**Comment by mariohamann** [comment]
Here's a draft for refinement:

## Description
We provide an `sd-table-cell` element that allows developers to quickly build tables with a defined style. (For Design it's a component, as this allows quick prototyping, for Development it could make sense to provide a CSS style instead. Let's call it just "element" for now.) The element doesn't handle semantics like `td`, `th`, `tr` etc. which is completely handled by the LightDOM instead. This serves a11y and a much easier implementation.

## API
https://www.figma.com/file/KyUiUXKhMLiwCfKYDRh2bO/Table?type=design&node-id=0-1&mode=design&t=VTsXIkJwgPDV5TUE-11

```ts
export interface sd-table{
	<slot>
	divider-right: boolean; 
	divider-left: boolean; 
	*shadow-right: boolean; 
	variant: 'transparent' | 'white' | 'primary-100' | 'neutral-100'; 
}
```

If we do it as CSS it would be:
```
sd-table-cell--divider-right
sd-table-cell--divider-left
sd-table-cell--transparent
sd-table-cell--white
sd-table-cell--primary-100
sd-table-cell--neutral-100
```

Currently in Figma two components are build, which only difference is `bold` or `not-bold` for header vs. `not-header`. We decided to merge this in a single `sd-table-cell` component and let the users mark headers with bold theirself.

On top we maybe should provide a `sd-table` class, which just removes all default styling in a table, so that paddings and borders etc. are cleared before using our component.

**Comment by mariohamann** [comment]
@MarcMatthiae 

```html
<!-- CSS Example -->

<table class="sd-table">
  <tr>
    <th class="sd-table-cell--divider-left sd-table-cell--divider-right">here it the content</th>
    <th class="sd-table-cell--divider-right">here it the content</th>
  </tr>
  <tr>
    <td class="sd-table-cell--divider-left sd-table-cell--divider-right">here it the content</td>
    <td class="sd-table-cell--divider-right">here it the content</td>
  </tr>
</table>
```

**Comment by karlbaumhauer** [comment]
@coraliefeil pls update the links to figma in the description

**Comment by coraliefeil** [comment]
In addition to sd-table WRT https://jira.apps.union-investment.de/browse/PSOLIDDS-2

What can we tell the procuct team concerning their request?

Can they built their tables using sd-scrollable or how could the implement it meeting their requirements?

Can we offer a sample for them?

**Comment by mariohamann** [comment]
The problem is, that `sd-scrollable` could break semantics in a table. I would propose to do a next iteration on that when @MarcMatthiae is done.

Maybe we can provide a style INSIDE the component that creates the shadow for a cell and we provide a minimal example including JS how others can implement it.

This serves the need, that designers can use it in their component, devs get the style + an example how to use it. Depending on upcoming feedback maybe we can adjust the sample in future.

**Comment by karlbaumhauer** [comment]
> The problem is, that `sd-scrollable` could break semantics in a table. I would propose to do a next iteration on that when @MarcMatthiae is done.
> 
> Maybe we can provide a style INSIDE the component that creates the shadow for a cell and we provide a minimal example including JS how others can implement it.
> 
> This serves the need, that designers can use it in their component, devs get the style + an example how to use it. Depending on upcoming feedback maybe we can adjust the sample in future.

#372
