### ISSUE TITLE
feat: ✨ add sd-headline

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#243]
This is tough one. It should be able to allow links, should contain a h1/h2/...-tag or could even be a p tag as described over here: https://www.tpgi.com/subheadings-subtitles-alternative-titles-and-taglines-in-html/

```html
<hgroup role="group" aria-roledescription="Heading group">
  <p aria-roledescription="subtitle">Magazine of the Decade</p>
  <h1>THE MONTH</h1>
  <p aria-roledescription="subtitle">The Best of UK and Foreign Media</p>
</hgroup>
```

I tend to use a slot for all of this and propose the following API:

```html
<hgroup role="group" aria-roledescription="Heading group">
  <sd-headline visual-level="4">
    <p aria-roledescription="subtitle">Magazine of the Decade</p>
  </sd-headline>
  <sd-headline visual-level="2">
    <h1>THE MONTH</h1>
  </sd-headline>
  <sd-headline visual-level="2">
    <p aria-roledescription="subtitle">The Best of UK and Foreign Media</p>
  </sd-headline>
</hgroup>
```

Or the other way round:
```html
<hgroup role="group" aria-roledescription="Heading group">
  <p aria-roledescription="subtitle"><sd-headline visual-level="4">
    Magazine of the Decade
  </sd-headline></p>
  <h1><sd-headline visual-level="2">
    THE MONTH</sd-headline></h1>
  <p aria-roledescription="subtitle"><sd-headline visual-level="2">
    The Best of UK and Foreign Media
  </sd-headline></p>
</hgroup>
```

It should be even possible to do something like this then:
```html
    <h3>
  <sd-headline visual-level="2">
    <sd-link>THE MONTH</sd-link>
  </sd-headline>
   </h3>
```

Not sure if this works the other way round if the sd-link is outside... (colors...)

Furthermore the whole content-icon thingy has to bee integrated. I believe we can reuse some logic from the `sd-link`.

![image](https://github.com/solid-design-system/solid/assets/26542182/2a53bee5-43e8-4434-a670-8ec8d9a25b4e)

`<mark>` should be green – let's think about providing this globally, as this will be slotted. Maybe this could be part of the styles of `solid-element` or in tailwind.css:

![CleanShot 2023-07-19 at 10 24 35](https://github.com/solid-design-system/solid/assets/26542182/5d5d70ae-4f73-4244-9366-bb49894e6f30)

Regarding icon see https://component-library.fe.union-investment.de/latest/storybook/index.html?path=/story/components-headline--configurable&args=icon:tree&globals=backgrounds.value:!hex(F6F6F6)

Regarding icon positioning: https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/story/components-sd-link--standalone-and-icon-slots

**Comment by mariohamann** [comment]
## Rethinking the Component
First of all: Going they route that the component doesn't provide any tags is definitely the right way as I realized, that many <h*>-parses don't recognize headlines in the ShadowDOM. This is definitely a problem.

Building on that, I believe the component should definitely just provide a <span> in the ShadowDOM with the correct styling. This makes it possible that devs can just wrap an <h2> or whatever outside of it and they are in charge of a11y. 

Thinking this further we could provide a <sd-typography> component, which contains even more styles:
- `<sd-typography style="leadtext">`
- `<sd-typography style="paragraph">`
- `<sd-typography style="headline-1">`
- `<sd-typography style="headline-2">`
- `<sd-typography style="headline-3">`
- `<sd-typography style="headline-4">`

## A more pragmatic approach: CSS?!
But taking this further: What is the benefit of a component having no logic at all which has only styles?
What about just providing a CSS file with pre-baked-classes?

- `<p class="sd-leadtext">`
- `<p class="sd-paragraph">`
- `<h2 class="sd-headline-1">`
- `<h2 class="sd-headline-2">`
- `<h2 class="sd-headline-3">`
- `<h2 class="sd-headline-4">`
- `<h2 class="sd-headline-5">`
- `<address class="sd-meta sd-meta--small">`
- `<address class="sd-meta sd-meta--light">`
- `<address class="sd-meta sd-meta--piped">`

### Possible problems 
- wrong styles could cascade, so all of those classes would have to be defined completely (line-height, character spacing, font size, font-color, etc., font-style)
- people creating Web Components with ShadowDOM theirself would have to include those styles inside their component (by including the CSS in their build scripts and/or by using <link>, but I#m not sure regarding browser support for the latter)


### Possible benefits
- better performance (less components + less rendering time!)
- much cleaner DOM
- maybe an closer behaviour with design, as they apparaently use text styles in Figma as well and creating the components was just for satisfying development

Any further thoughts? Let me here.

**Comment by SheepFromHeaven** [comment]
Looking at borth alternative options, I would personally prefer the sd-typography component for the following reasons:

1. Developers coming from React are used to a <Typography> component (https://mui.com/material-ui/react-typography/)
2. Adding CSS classes, means adding a whole new field of knowledge. This is like assing tailwind to a React project. I suddenly need to have tow areas of knowledge instead of one. Also 2 sources for errors / bugs
3. We have ONE component to handle general styling. One single source of truth.

**Comment by mariohamann** [comment]
Thanks for chiming in and your perspective! I will take your thoughts into consideration, especially the aspect of unity by providing a single source of truth.

Personally I'm not a proponent for "styling components" as Chakra etc. does, as this can harm performance and I believe setting classes can be expected as "basic toolkit" for every web developer.

Thanks for this perspective!

**Comment by mariohamann** [comment]
I updated some thoughts in the [comment](https://github.com/solid-design-system/solid/issues/243#issuecomment-1643581512) for styles which have options like e. g. `<sd-meta>` or `<sd-display>` which could even conflict with each other when providing them as a component.

**Comment by abudd1094** [comment]
My perspective is a bit limited but I tend to agree with Marc; component oriented thinking prevails.

I expect a component library to provide me with components and not classes.  So the approach of developing sd-typography as a child component to be slotted in sd-headline makes the most conceptual sense.  Otherwise, I start to have a hybrid library that provides both components and classes; this inevitably becomes more complicated to understand and use (as intended).  By providing a component and demonstrating how it can be slotted, you reduce the complexity for users and ensure a more consistent implementation.

This reminds me of the header in some way because it uses complementary components like navigation and service-area to build it's intended interface.  

In the end, I could work with either given the appropriate documentation, and I am not sure about the performance tradeoffs...  In this day and age, is it really a big difference?  Would the component approach have a noticeable impact on performance?  I have less experience seeing how these things play out long term but would imagine those differences are constantly diminished.

**Comment by mariohamann** [comment]
Thanks for your valuable feedback – either way we go, we definitely have to have DX in mind.

Furthermore I'm realizing, that documentation and reasoning might be the most important part if we go the CSS classes route. This really helps A LOT.

**Comment by yoezlem** [comment]
@abudd1094 Thanks for your thoughts! :) 
Could you explain why you would need an additional component precisely? Even with the sd-headline component, you would still have to differentiate which H-tag and font size you require 🤔
Or is it simply more readable for you when you add these classes into sd-headline, sd-meta, sd-address, etc.?

**Comment by mariohamann** [comment]
![CleanShot 2023-07-20 at 15 23 19](https://github.com/solid-design-system/solid/assets/26542182/8c5ea535-c58a-466b-a769-557f1180a919)

We're now evaluating the CSS approach for the beforementioned components and especially have a look how we can document this appropriately. You can follow along over here: https://github.com/solid-design-system/solid/pull/246

As long as we don't now the final direction, I'm going to block this ticket here.

Thanks for everyone having joined this discussion (as well here as privately on chat – the feelings are definitely mixed, and I like that!)

**Comment by christophsaile** [comment]
Personally I like this CSS approach for this "text-styling" use case because it doesn't add extra elements to the dom and it's easy to use. If I start using a new component library I will go first to the storybook and check the code example. With this example I think it is easy to understand how this concept of baked classes work and every developer should be able to apply this.

**Comment by mariohamann** [comment]
As this was more a research ticket I'm closing this in favor of https://github.com/solid-design-system/solid/issues/367.

Thanks for anyone participating!
