### ISSUE TITLE
feat: ✨ add sd-brand-shape

### ISSUE THREAD

**Issue by mariohamann** [solid-design-system/solid#245]
![CleanShot 2023-07-19 at 15 17 36](https://github.com/solid-design-system/solid/assets/26542182/2af2db1c-c1d2-4171-a3f1-2e3fda7e2f6a)

Coming from the sd-container, we need the sd-brand-shape.

1. I already refactored the SVG from a Design perspective, that it can handle border and background seperately.
2. Furthermore it should be able to resize itselft, but always preserve the aspect-ration of the shape.
3. Regarding the border, it should alway be 2 px, even if it resizes.

**Comment by christophsaile** [comment]
We agreed on that for the first version of the component we won't include the variants which have a border.
The reason for this is that we were no able to create a svg that preservers its ratio when scaling but preserves the 2px border at any scale.
We tried the following approches:

 - adjust viewbox
 - different optimized svg versions
 - add vector-effect="non-scaling-stroke", which led the svg to beeing out of the viewbox on mobile screens
 - using fill for the strokes
 - creating a svg for top, center and bottom so we don't have a mismatch between a svg and div 

The main problem was that with the option vector-effect="non-scaling-stroke" you can preserve the 2px border at any scale, but because the border gets relatively bigger on small viewports the svg got cut off.

**Comment by van-nguyen-ht** [comment]
Here's the iterated figma file
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/s7zl5cMsCXzG0gp670AFmu/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=8713-2967&mode=design&t=q0hqtnJmsURsumBX-11

**Comment by van-nguyen-ht** [comment]
Here's the iterated figma file
https://www.figma.com/file/VTztxQ5pWG7ARg8hCX6PfR/branch/s7zl5cMsCXzG0gp670AFmu/Solid-DS-%E2%80%93-Component-Library?type=design&node-id=8713-2967&mode=design&t=q0hqtnJmsURsumBX-11
