### ISSUE TITLE
research: max. letters per line – implement new figma feat?

### ISSUE THREAD

**Issue by coraliefeil** [solid-design-system/solid#556]

**Comment by yoezlem** [comment]
Any new Information here @coraliefeil @van-nguyen-ht?

**Comment by van-nguyen-ht** [comment]
Abstract: 
-To use ch as a based unit for column width as it stands from. [Source](https://drafts.csswg.org/css-values-3/#ch)

Experimenting method: 
-make a column n characters wide
-define 0 width as base ch unit and multiply with n
-test with available plugin [Line Length](https://www.figma.com/community/plugin/875546357676392881/line-length)
-calculate an average value, if it correspond to the actual average character width in any given column, since actual letter form distribution in ordinary text in non-uniform. It even varies by language.

Result: 
-Other than for monospace fonts (which UI Frutiger is not), it does not correspond to the average width of the letters.
