### ISSUE TITLE
research: using third party library for autosuggest

### ISSUE THREAD

**Issue by karlbaumhauer** [solid-design-system/solid#686]
## Task 
In order to simplify the upcoming `sd-autosuggest` component and create a maintainable solution, https://github.com/algolia/autocomplete could be a good way to go. Before we start implementing it in #269 the service should be evaluated. 

Results should be documented in this ticket and in case we plan to use the autocomplete from Algolia, any findings for the future implementation should be added to the ticket #269 .

**Comment by Vahid1919** [comment]
The main goal of this research was to see if algolia's autocomplete feature can create `sd-input` instead of an `input` element. From what I could find so far this is not possible through a configuration of Algolia.

While setting up Algolia, the only HTML we use is for the container: 
```html
<div id="autocomplete"></div>
```
Everything else is setup in Javascript side and there is not a configuration option to change the <input> Element. 

I additionally took a look at a more advanced section called [Creating a custom renderer](https://www.algolia.com/doc/ui-libraries/autocomplete/guides/creating-a-renderer/) that provided more granular options to manipulate the autocomplete feature. But this also ended up being limited only allowing you to pass props to and from the `<input>` and not changing it in any meaningful way. 

In this[ sandbox](https://codesandbox.io/p/sandbox/github/algolia/autocomplete/tree/next/examples/react-renderer?file=%2Fsrc%2FAutocomplete.tsx) you can find a complete setup of all the configuration options.I attempted to replace `<input>` with `<sd-input>` and that does break the autocomplete feature. 

Finally I took a look at the packages in the [algolia/autocomplete repository](https://github.com/algolia/autocomplete/tree/next/packages). I found an [Input component](https://github.com/algolia/autocomplete/blob/next/packages/autocomplete-js/src/elements/Input.ts) that was defined in the `autocomplete-js` package. It looks like here is where the input HTML element is created. Perhaps here is where we could try to integrate sd-input.

This has been the bulk of my research so far. I wanted to communicate the current progress and ask you (@solid-design-system/core-development) if it makes sense to try and replace the input component and see if it would work before I attempted that solution.

**Comment by karlbaumhauer** [comment]
@Vahid1919 thx for the update. IMO it makes sense if the package itself (except the input vs sd-input issue) would help us building the sd-autosuggest component. What do you think?

**Comment by Vahid1919** [comment]
Reassigning to you @mariohamann since you're taking over here.

**Comment by mariohamann** [comment]
So @Vahid1919 and me had some look on the Algolia stuff.

We thought about different routes:
1. Use `@algolia/autosuggest-core`: This expects us to build an own https://www.algolia.com/doc/ui-libraries/autocomplete/guides/creating-a-renderer/
2. Use `@algolia/autosuggest-js`: This would expect us to build an own CSS and Algolia would just create complete DOM elements. Vahid started working on that, to see how far he can go. On that we realized two problems:
  1. The `submit` button and the clearable button are both tabable – what AFAIK is not recommended in terms of A11y. There's no way to override it.
  2. The icons are not easy to exchange: https://support.algolia.com/hc/en-us/articles/16404134213905-How-can-I-change-the-submit-button-icon-in-my-AutoComplete-search-bar
  3. While having on that issue, we've got aware of the following issue: https://support.algolia.com/hc/en-us/articles/14424771026833-Can-I-have-two-AutoComplete-SearchBoxes-on-the-same-page- In fact that's a total blocker for using `autosuggest-js`.

I'm now having a look into `autosuggest-core` now, to see if this could be utilized to build a web component or similar. Let's see...

Thanks for the work, so far @Vahid1919 !
