### ISSUE TITLE
fix: 🤔 No versioned "sd-change" event for sd-radio-group and sd-checkbox triggered

### ISSUE THREAD

**Issue by clemens-vi** [solid-design-system/solid#981]
## Current behavior
in the sd-components "sd-radio-group" and "sd-checkbox" the custom "change" event is only available via "sd-change", but not versioned e.g. as "sd-2-11-0-change". (versioned event works eg. for "sd-input" or "sd-2-11-0-input".

Also clarify, check and fix: Does this affect also other sd-components and/or other custom events?

## Expected behavior
for both "sd-radio-group" and "sd-checkbox" triggering versioned event strings, these events are dispatched the same way as non-versioned events like "sd-change"

## Steps to reproduce
Using "sd-radio-group" and/or "sd-checkbox" SD Version 2-11-0:
create event triggers for "sd-change" -> event dispatched  ✅
create event triggers for "sd-2-11-0-change"  -> **no event dispatched** 🚫

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

**Comment by mariohamann** [comment]
Hey @clemens-vi !

Thanks for raising the issue.

Actually the event names shouldn't be versioned. This is a bug in our version pipeline. Instead, all events should have no version number in it.

This will be fixed in the following PR: https://github.com/solid-design-system/solid/pull/995

From that on, all event names, including `sd-input` should be unversioned.
